spring.application.name=gis
# 1. Cấu hình kết nối PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/gialai
spring.datasource.username=gmios
spring.datasource.password=25082005
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Cấu hình JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ddl-auto: 
# - Chọn 'validate' để Hibernate chỉ kiểm tra xem các class Entity có khớp cấu trúc với DB hay không (Khuyên dùng vì bạn đã chạy DDL.sql thủ công).
# - Chọn 'none' nếu không muốn kiểm tra.
spring.jpa.hibernate.ddl-auto=validate

# Lưu ý: Từ Hibernate 6 (Spring Boot 3.x), Hibernate tự động nhận diện tính năng Spatial 
# của PostgreSQL nên bạn không cần chỉ định cứng PostgisDialect nữa.
spring.security.user.name=admin
spring.security.user.password=123456